name: video_downloader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.4.1
  easy_localization: ^3.0.7
  process_run: ^1.2.2+1
  file_picker: ^8.3.1
  package_info_plus: ^8.2.1
  shared_preferences: ^2.3.3
  bitsdojo_window: ^0.1.6
  drift: ^2.23.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1

dependency_overrides:
  logging: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.23.0
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/executable/
     - assets/translations/


